### ISSUE TITLE
Freeshow fails to start

### ISSUE THREAD

**Issue by paulprince** [ChurchApps/FreeShow#1157]
Launching freeshow throws "There is no built binary for font-manager" error on my Linux system. 

Launching freeshow on my Linux computer. 

A JavaScript error occurred in the main process
Uncaught Exception:
Error: There is no built binary for font-manager
    at Object.<anonymous> (/tmp/.mount_FreeSh0TJFG6/resources/app.asar/node_modules/font-scanner/index.js:8:11)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/tmp/.mount_FreeSh0TJFG6/resources/app.asar/node_modules/css-fonts/dist/index.js:16:40)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed

 - OS: [Linux]
 - FreeShow Version:1.3.3.

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/1119
