### ISSUE TITLE
[Bug Report] Can't open the app. "Unexpected end of JSON input"

### ISSUE THREAD

**Issue by MiragePresent** [ChurchApps/FreeShow#755]
**Describe the bug**
I was trying to configure sync files to the cloud. Probably it messed up the files and now I can't open the app:
```
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at Conf._deserialize (/Applications/FreeShow.app/Contents/Resources/app.asar/node_modules/conf/dist/source/index.js:67:43)
at get store [as store] (/Applications/FreeShow.app/Contents/Resources/app.asar/node_modules/conf/dist/source/index.js:278:43)
at new Conf (/Applications/FreeShow.app/Contents/Resources/app.asar/node_modules/conf/dist/source/index.js:131:32)
at new ElectronStore (/Applications/FreeShow.app/Contents/Resources/app.asar/node_modules/electron-store/index.js:69:3)
at Object.<anonymous> (/Applications/FreeShow.app/Contents/Resources/app.asar/build/electron/data/store.js:2:837)
at Module._compile (node:internal/modules/cjs/loader:1120:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
```

**Reproducing**
Unfortunately I cannot. The app was working yesterday while I was trying to set up Google drive sync. Today I can't open it

**Screenshots (Optional)**
I
![Screenshot 2024-08-15 at 11 03 16 PM](https://github.com/user-attachments/assets/3639dde2-e2f1-4018-b979-825dcb210b02)

**Version (Optional)**
 - OS: MacOS
 - FreeShow Version: 1.2.4 (tried to downgrade to 1.2.2 - same result)

**Additional context**
1. Were do I find a log file to get more details about the error. Maybe I can remove/fix a file and it'll work?
2. I tried to remove the `~/Documents/FreeShow` (data location folder) so the app recreates all the files. Still the same problem

**Comment by vassbo** [comment]
All right, the problems is not with your .show files (songs) so you can keep those. please navigate to `~/Library/Application Support/FreeShow/` or find the app data location if it's not there. Then send over the .json files so I can try fix this. When you have done that you can delete all the .json files here to fix the issue! :)

**Comment by vassbo** [comment]
I added a check to automatically delete any files that can't be parsed correctly for the next version.
So you can just wait for that if you want. Sorry for the inconvenience.

**Comment by MiragePresent** [comment]
@vassbo Thank you for instructions. For some reason the `error_log.json` was empty. I removed it and now everything works
